"""
Edhir ML Service — Week 3 placeholder implementation.

This file has two responsibilities:
  1. FastAPI HTTP endpoint (GET /score, POST /score) — kept from Week 1 for
     circuit-breaker health checks.
  2. RabbitMQ consumer thread — receives RequestMetadata JSON messages from
     the proxy-service, computes a simple velocity-based anomaly score, and
     writes it back to sessions.current_score in Postgres.

Week 3 scoring logic (PLACEHOLDER — will be replaced in Week 4):
  - Count how many requests came from the same session_id in the last 60 s.
  - Map linearly: 0 requests → 0, ≥20 requests → 100.
  - This is purely request-velocity; no Isolation Forest model is used yet.
  - See comment block at bottom of compute_score() for Week 4 design notes.
"""

import json
import os
import threading
import time

import pika
import psycopg2
import psycopg2.extras
from fastapi import FastAPI

# ── Config from environment (falls back to docker-compose defaults) ────────────
DB_HOST = os.getenv("DB_HOST", "postgres")
DB_PORT = int(os.getenv("DB_PORT", "5432"))
DB_NAME = os.getenv("DB_NAME", "edhir")
DB_USER = os.getenv("DB_USER", "user")
DB_PASS = os.getenv("DB_PASS", "password")

RABBIT_HOST = os.getenv("RABBIT_HOST", "rabbitmq")
RABBIT_PORT = int(os.getenv("RABBIT_PORT", "5672"))
QUEUE_NAME = "request.metadata"

VELOCITY_WINDOW_SECS = 60
VELOCITY_MAX = 20  # requests in window that maps to score 100

app = FastAPI()


# ── FastAPI health endpoints (kept from Week 1) ────────────────────────────────

@app.get("/score")
def score_get():
    return {"status": "ML Service is up", "note": "Week 3 placeholder"}


@app.post("/score")
def score_post(body: dict = None):
    return {"note": "Velocity scoring runs via RabbitMQ consumer, not HTTP POST"}


# ── Postgres helper ────────────────────────────────────────────────────────────

def get_db_conn():
    return psycopg2.connect(
        host=DB_HOST, port=DB_PORT, dbname=DB_NAME,
        user=DB_USER, password=DB_PASS
    )


# ── Week 3 placeholder scoring ─────────────────────────────────────────────────

def compute_score(session_id: str, conn) -> float:
    """
    WEEK 3 PLACEHOLDER — simple request-velocity score.

    Counts the number of requests in the requests table for this session_id
    in the last VELOCITY_WINDOW_SECS seconds and scales linearly to 0-100.

    ──────────────────────────────────────────────────────────────────────────
    WEEK 4 PLAN (Isolation Forest model):
      - Replace this function with a call to a trained IsolationForest that
        operates on a feature vector: [velocity, path_entropy, method_mix,
        ua_consistency, time_of_day_bin].
      - The model will be loaded once at startup from a serialised .pkl file
        generated by the training pipeline in ml-service/train.py.
      - Score will be the model's decision_function() output mapped to 0-100.
    ──────────────────────────────────────────────────────────────────────────
    """
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT COUNT(*) FROM requests
            WHERE session_id = %s::uuid
              AND timestamp >= NOW() - INTERVAL '%s seconds'
            """,
            (session_id, VELOCITY_WINDOW_SECS)
        )
        count = cur.fetchone()[0]

    raw_score = min(count / VELOCITY_MAX, 1.0) * 100.0
    return round(raw_score, 2)


def update_session_score(session_id: str, score: float, conn) -> None:
    with conn.cursor() as cur:
        cur.execute(
            "UPDATE sessions SET current_score = %s WHERE id = %s::uuid",
            (score, session_id)
        )
    conn.commit()


# ── RabbitMQ consumer (runs in a background thread) ───────────────────────────

def on_message(ch, method, properties, body):
    try:
        data = json.loads(body)
        session_id = data.get("sessionId")
        if not session_id:
            ch.basic_ack(delivery_tag=method.delivery_tag)
            return

        conn = get_db_conn()
        try:
            score = compute_score(str(session_id), conn)
            update_session_score(str(session_id), score, conn)
        finally:
            conn.close()

    except Exception as e:
        print(f"[ml-service] Error processing message: {e}")
    finally:
        ch.basic_ack(delivery_tag=method.delivery_tag)


def start_consumer():
    """Retry-loop: wait for RabbitMQ to be ready, then start consuming."""
    while True:
        try:
            connection = pika.BlockingConnection(
                pika.ConnectionParameters(host=RABBIT_HOST, port=RABBIT_PORT)
            )
            channel = connection.channel()
            channel.queue_declare(queue=QUEUE_NAME, durable=True)
            channel.basic_qos(prefetch_count=1)
            channel.basic_consume(queue=QUEUE_NAME, on_message_callback=on_message)
            print(f"[ml-service] Consumer started on queue '{QUEUE_NAME}'")
            channel.start_consuming()
        except Exception as e:
            print(f"[ml-service] Consumer error, retrying in 5s: {e}")
            time.sleep(5)


# Start the consumer in a daemon thread so FastAPI startup is not blocked
consumer_thread = threading.Thread(target=start_consumer, daemon=True)
consumer_thread.start()
