version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/proxy-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/ml-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/dashboard"
    schedule:
      interval: "weekly"
